version: '3.0'

services:
  api:
    container_name: api
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
      - 9229:9229
    command: yarn start:dev
    depends_on:
      - db
    links:
      - db
    restart: always
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event-calendar
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  db-data:
